apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true
- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
    - matcherRegex: "\"obu_id\":\"(\\d+)\""
      name: Search
      url: 'https://www.google.com/search?q=$${__value.raw}'
      internalLink: false
